//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFM_T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFM_Product
    {
        public int RowId { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string UnitPathId { get; set; }
        public string Item { get; set; }
        public string Amount { get; set; }
        public string Size { get; set; }
        public string Kind { get; set; }
        public string OriginalHolder { get; set; }
        public string Worth { get; set; }
        public string Material { get; set; }
        public string ObjectTime { get; set; }
        public string Maker { get; set; }
        public string Status { get; set; }
        public string Place { get; set; }
        public string ImageUrl { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserId { get; set; }
        public string Cancel { get; set; }
    }
}
