//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFM_T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFM_USER
    {
        public int RowId { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string MyPhone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public int PermissionId { get; set; }
        public string UnitPathId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserId { get; set; }
    }
}
