//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFM_T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFM_UNIT
    {
        public int RowId { get; set; }
        public string ParentName { get; set; }
        public string ParentNoteId { get; set; }
        public string UnitName { get; set; }
        public string UnitPathId { get; set; }
        public string ManagementUnit { get; set; }
        public string Location { get; set; }
        public Nullable<int> UnitAmount { get; set; }
        public string UnitMark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserId { get; set; }
    }
}
