//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFM_T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFM_CheckList
    {
        public int RowId { get; set; }
        public string CID { get; set; }
        public string ProductID { get; set; }
        public string UnitPathId { get; set; }
        public string CheckResult { get; set; }
        public string CheckMark { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string CheckStatue { get; set; }
        public string CheckListStatue { get; set; }
    }
}
